### ISSUE TITLE
Clarification Please?

### ISSUE THREAD

**Issue by rPromptt** [mrthetkhine/RBFNeuralNetwork#1]
Hi, 

Please note that this’s rather a request for clarification than an issue.

In line 45, why did you define p = hidden./3

In line 144, are you  performing the normalised radial basis functions network (NRBFN) instead of standard rbf?

You seem to have two functions:

def setup_sigma_spread_radius

def setup_sigma_for_centre. 

What’s their difference please?

**Comment by mrthetkhine** [comment]
for line 45, I just experimenting the sigma value.
for 144, If we don't normalize the data output, the result will not be corrupt
Spread radius define how far the centroid will effect the incoming neuron. The more spread radius, the centroid will have much effect on matching input near the centroid.
Center is just needed in RBF for calculating the input to weight.

**Comment by rPromptt** [comment]
Hi, I understand very clearly the theory supporting RBFN, centroids, spread, hidden to output weights ... etc. But my question is: why do you have two functions sigma spread radius and sigma for centre which both appear to be performing the same task. Why p = hidden/3. Finally, is this a normalised radial basis functions network or a standard rbf (reference to line 144)

**Comment by mrthetkhine** [comment]
Maintaining two sigma is just for experiment and it also true for p= hidden/3.
It is a normalized RBF.

**Comment by mrthetkhine** [comment]
We need to compute sigma and I just put the constant to ease the code.

**Comment by Kay9Man** [comment]
Thanks for clarifying. I’ll comment out the function: def sigma_for_centre, and the constant p, to see if everything will still work fine. One last thing please - could you also write a demo code for the prediction at test point, ie test = predict(model = RBFNEuralNetwork, newdata = testdata).

**Comment by mrthetkhine** [comment]
I already have the code written for testing, I cannot give more time for
that , sorry.

**Comment by Kay9Man** [comment]
that's ok. thanks for your time.
